<a href="https://colab.research.google.com/github/angrybird05/pyTorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu126


introduction to tensor and

creating a tensor

In [ ]:
import torch

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
import torch
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
import torch
#tensor
tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
tensor
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.requires_grad)

torch.Size([1, 3, 3])
torch.int64
cpu
False


In [ ]:
#ARTHAMATIC OPERATONS

import torch
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
add=x+y
sub=x-y
mul=x*y
div=x/y
print(add,sub,mul,div)


tensor([10, 10, 10]) tensor([-8, -6, -4]) tensor([ 9, 16, 21]) tensor([0.1111, 0.2500, 0.4286])


In [ ]:
#MATRIX MULTIPLICATION (dot product)
import torch
matrix1 = torch.tensor([[7,8],[9,10]])
matrix2=torch.tensor([[1,2],[3,4]])
print(torch.matmul(matrix1,matrix2))

#ELEMENT WISE MULTIPLICATION
print(matrix1*matrix2)


tensor([[31, 46],
        [39, 58]])
tensor([[ 7, 16],
        [27, 40]])


In [ ]:
#creating Random tensor
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)
print(random_tensor.dtype)
print(random_tensor.device)
print(random_tensor.requires_grad)

tensor([[7.5644e-01, 4.4676e-02, 9.2770e-01, 3.7593e-01],
        [6.4045e-04, 5.3931e-01, 1.9848e-01, 1.1925e-01],
        [7.0267e-01, 1.5425e-01, 5.4120e-01, 4.2770e-01]])
2
torch.float32
cpu
False


In [ ]:
### getting information from tensor
import torch
rand_tensor = torch.rand(4,5)
print(rand_tensor)
print(rand_tensor.dtype)
print(rand_tensor.shape)
print(rand_tensor.device)


tensor([[0.4743, 0.8710, 0.8145, 0.5758, 0.8467],
        [0.1545, 0.8932, 0.5655, 0.2173, 0.0717],
        [0.3939, 0.5515, 0.5989, 0.2605, 0.6667],
        [0.9944, 0.3365, 0.6066, 0.3056, 0.4777]])
torch.float32
torch.Size([4, 5])
cpu


In [ ]:
   ## finding min, max,mean,sum,etc(tensor aggregation)
import torch
x=torch.arange(0,100,10)
x
print(f"min: {x.min()}")
print(f"max: {x.max()}")
print(f"mean: {x.type(torch.float32).mean()}")
print(f"sum: {x.sum()}")
print(f"index of min value: {x.argmin()}")
print(f"index of max value: {x.argmax()}")


min: 0
max: 90
mean: 45.0
sum: 450
index of min value: 0
index of max value: 9


In [ ]:
    ## reshaping , stacking ,Squeezing and unsqueezing tensors
import torch

    x=torch.arange(1.,10.)
    print(f"orginal Tensor is {x},the shape of the orginal tensor is {x.shape}")
    x_reshaped = x.reshape(1,9)
    print(f"Reshaped Tensor{x_reshaped,x_reshaped.shape}")
    print("\n")


    #stacking a Tensor
    print("stacking the tensor\n")
    x_stacked = torch.stack([x,x,x,x],dim=0)
    print(f"stacked Tensor is {x_stacked}")
    print("\n")

    #squeezing the tensor
    print("squeezing the tensor\n")
    x_reshaped = x.reshape(9,1)
    print(f"the squeezed tensor is {x_reshaped}")

    print("\n")

    #unsqueezing the tensor
    print("unsqueezing the tensor\n")
    x_unsqueezed = x_reshaped.squeeze()
    print(f"orginal tensor{x_reshaped}")
    print(f"the unsqueezed tensor is {x_unsqueezed}")

    print("\n")

    #changing the view of the tensor
    print("changing the view of the tensor\n")
    z=x.view(1,9)
    print(f"\n the view tensor is {z}")

    print("\n")

    # Permuting the tensor
    print("Permute the tensor\n")
    # Fix: Create a 3D tensor to match the permute operation
    x_original = torch.rand(size=(224,224,3),dtype=torch.float32) # Example: 224x224 image with 3 channels
    x_permuted = x_original.permute(2,0,1)
    print(f"original shape: {x_original.shape}")
    print(f"permuted shape: {x_permuted.shape}")


orginal Tensor is tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),the shape of the orginal tensor is torch.Size([9])
Reshaped Tensor(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))


stacking the tensor

stacked Tensor is tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])


squeezing the tensor

the squeezed tensor is tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


unsqueezing the tensor

orginal tensortensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
the unsqueezed tensor is tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


changing the view of the tensor


 the view tensor is tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])


Permute the tensor

original shape: torch.Size([224, 224, 3]

In [16]:
## Indexing on the tensor
import torch
x=torch.rand(4,4)
print(f"the orginal tensor is {x}")
print(f"the second row of the tensor is: {x[1]}")
print(f"the second column of the tensor is: {x[:,1 ]}")
print(f"the last column of the tensor is: {x[:,-1]}")
print(f"the last row of the tensor is: {x[-1]}")

the orginal tensor is tensor([[2.2322e-04, 5.7575e-01, 3.8844e-01, 7.1276e-01],
        [6.1023e-01, 1.7561e-01, 8.5279e-01, 3.2502e-01],
        [8.9529e-01, 6.7776e-01, 1.3689e-02, 8.7652e-01],
        [2.0362e-02, 2.3915e-01, 3.8658e-02, 8.4984e-01]])
the second row of the tensor is: tensor([0.6102, 0.1756, 0.8528, 0.3250])
the second column of the tensor is: tensor([0.5757, 0.1756, 0.6778, 0.2392])
the last column of the tensor is: tensor([0.7128, 0.3250, 0.8765, 0.8498])
the last row of the tensor is: tensor([0.0204, 0.2392, 0.0387, 0.8498])


In [19]:
## Numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

# CHANGING THE VALUE IN ARRAY
array=array+2
array,tensor




(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [22]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor
# changing the tensor
tensor=tensor+2
tensor,numpy_tensor


(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))